### PR TITLE
Implement array type fields

### LINKED ISSUE #147: Implement array type fields
Let's handle array type fields that look like this:

"a,b,c,d,e"

And splitting on commas.

### PR DESCRIPTION
**Pull request by evz**
Closes #147

### CODE REVIEW

**Comment by fgregg** [comment]
What about this approach here: 

http://stackoverflow.com/questions/15721363/preserve-python-tuples-with-json

**Comment by evz** [comment]
The problem is that the training data is a dict of containing lists of dicts. Attempting to find which list is the right one was kinda tricky and the solution looked a bit like [this](https://github.com/datamade/dedupe-api/blob/60080f408abafda80a90726ce1bb70909560b688/api/utils/helpers.py#L108-L121) anyways.

**Comment by evz** [comment]
The other half of the problem was that storing things in the database as arrays was very useful but SQLAlchemy converts those to lists by default when fetching them from the DB. There's a way to override it but it involved using logic like [this](https://github.com/datamade/dedupe-api/blob/60080f408abafda80a90726ce1bb70909560b688/api/utils/helpers.py#L276-L289) instead of using raw SQL (which I prefer, believe me).

**Comment by fgregg** [comment]
Hmm.. I actually think that logic might better belong here:

https://github.com/datamade/dedupe/blob/5a9e800546f4b0d184006315b1fccdb7e8690b7d/dedupe/core.py#L356

**Comment by fgregg** [comment]
On the DB side, can we use: http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#sqlalchemy.dialects.postgresql.ARRAY.params.as_tuple

**Comment by evz** [comment]
Yup, already doing that: https://github.com/datamade/dedupe-api/blob/60080f408abafda80a90726ce1bb70909560b688/api/utils/helpers.py#L417-L424 That was really the only way I could get the set type fields to work.

**Comment by fgregg** [comment]
Seems like a good opportunity to subclass the Array type, http://docs.sqlalchemy.org/en/latest/core/custom_types.html

It's a little confusing that all the other types know how what to do with their own data, but this one doesn't.

**Comment by evz** [comment]
I'm not sure that would save any complexity. Since we're mostly using the SQL expression generator side of SQLAlchemy (especially for the parts that use that array field) we're not really declaring field types ahead of time but inferring them from the database. Which mostly works, just not in this case. 

We might actually get farther implementing a custom dialect: http://docs.sqlalchemy.org/en/rel_0_9/core/internals.html#sqlalchemy.engine.default.DefaultDialect This might actually pay off farther down the road if we want to do any other custom stuff.

**Comment by evz** [comment]
More on that: http://docs.sqlalchemy.org/en/rel_0_9/core/connections.html#registering-new-dialects

**Comment by fgregg** [comment]
This looks great! Let's do this.

**Comment by fgregg** [comment]
For reading and writing to json, you can now just use the dedupe serializer: https://github.com/datamade/dedupe/commit/1e60b716a434b7f4c4bb0d34cee7967ae38582b7

**Pull request merged**
